export const Items = [
  {
    id: 1,
    eventDate: "2023-03-05",
    clientName: "Tommy Moss",
    amount: "1200",
    status: "canceled",
    clientEmail: "client@1abc.com",
  },
  {
    id: 2,
    eventDate: "2023-03-07",
    amount: "1300",
    clientName: "Steven Flores",
    status: "canceled",
    clientEmail: "client@2abc.com",
  },
  {
    id: 3,
    eventDate: "2023-03-02",
    amount: "1400",
    clientName: "Ebony Chandler",
    status: "confirmed",
    clientEmail: "client@3abc.com",
  },
  {
    id: 4,
    eventDate: "2023-03-06",
    amount: "1250",
    clientName: "Randolph",
    status: "confirmed",
    clientEmail: "client@4abc.com",
  },
  {
    id: 5,
    eventDate: "2023-03-33",
    amount: "120",
    clientName: "Jennifer Stevenson",
    status: "canceled",
    clientEmail: "client@5abc.com",
  },
  {
    id: 6,
    eventDate: "2023-03-09",
    amount: "2200",
    clientName: "Gustavo Nash",
    status: "confirmed",
    clientEmail: "client@6abc.com",
  },
  {
    id: 7,
    eventDate: "2023-03-01",
    amount: "3200",
    clientName: "Naomi Hale",
    status: "confirmed",
    clientEmail: "client@7abc.com",
  },
  {
    id: 8,
    eventDate: "2023-03-21",
    amount: "9200",
    clientName: "Elias Sparks",
    status: "confirmed",
    clientEmail: "client@8abc.com",
  },
  {
    id: 9,
    eventDate: "2023-03-05",
    amount: "111200",
    clientName: "Carrie Russell",
    status: "canceled",
    clientEmail: "client@abc.com",
  },
  {
    id: 10,
    eventDate: "2023-03-11",
    amount: "100",
    clientName: "Ginger Carpenter ",
    status: "confirmed",
    clientEmail: "client@abc.com",
  },
  {
    id: 11,
    eventDate: "2023-03-10",
    amount: "120",
    clientName: "Joel Delgado ",
    status: "confirmed",
    clientEmail: "client@abc.com",
  },
  {
    id: 12,
    eventDate: "2023-03-07",
    amount: "2200",
    clientName: "Bryant Gill",
    status: "confirmed",
    clientEmail: "client@abc.com",
  },
  {
    id: 13,
    eventDate: "2023-03-07",
    amount: "3200",
    clientName: "Belinda Cummings",
    status: "confirmed",
    clientEmail: "client@abc.com",
  },
  {
    id: 14,
    eventDate: "2023-03-07",
    amount: "9200",
    clientName: "Tommy Moss",
    status: "postponed",
    clientEmail: "client@abc.com",
  },
  {
    id: 15,
    eventDate: "2023-03-03",
    amount: "111200",
    clientName: "Adrienne Burke",
    status: "confirmed",
    clientEmail: "client@abc.com",
  },
  {
    id: 16,
    eventDate: "2023-03-07",
    amount: "120",
    clientName: "Sammy Sharp",
    status: "postponed",
    clientEmail: "client@abc.com",
  },
  {
    id: 17,
    eventDate: "2023-03-07",
    amount: "2200",
    clientName: "Hugh Jackson",
    status: "canceled",
    clientEmail: "client@abc.com",
  },
  {
    id: 18,
    eventDate: "2023-03-07",
    amount: "3200",
    clientName: "Darnell Cunningham",
    status: "postponed",
    clientEmail: "client@abc.com",
  },
  {
    id: 19,
    eventDate: "2023-03-07",
    amount: "9200",
    clientName: "Regina Black",
    status: "canceled",
    clientEmail: "client@abc.com",
  },
  {
    id: 20,
    eventDate: "2023-03-30",
    amount: "111200",
    clientName: "Toni Wallace",
    status: "postponed",
    clientEmail: "client@abc.com",
  },
];
